name: CI
on: [push]
jobs:
  fribidi:
    name: Fribidi
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install vcpkg and packages
        uses: lukka/run-vcpkg@v7
        id: runvcpkg
        with:
          vcpkgGitCommitId: b67fab9861239e33b722b9a44f5c96dec6ca807e
          vcpkgTriplet: arm64-windows
          vcpkgArguments: fribidi
      - name: Upload log
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: fribidi output
          path: vcpkg/buildtrees/*
