name: CI
on: [push]
jobs:
  fribidi:
    name: Fribidi
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: arm64-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          vcpkgGitCommitId: b328539dd9c022e3f11b267ef68f11ad3a85eaf8
      - name: Install packages
        run: |
          vcpkg install
      - name: Upload log
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: fribidi output
          path: vcpkg/buildtrees/*
